# Changes here will be overwritten by Copier
_commit: 432d957
_src_path: https://github.com/worldworm/copier-base.git
copyright_year_start: 2023
copyright_year_today: 2023
project_description: Copier meta template for quasar projects.
project_emoji: 📋
project_name: copier-quasar-meta
repository_name: copier-quasar-meta
repository_provider: GitHub
repository_url: https://github.com/worldworm/copier-quasar-meta
repository_username: worldworm

