name: Lint

on:
  push:
    paths:
      - ".github/workflows/lint.yml"
      - ".eslintrc.cjs"
      - "**.vue"
      - "**.ts"
  pull_request:

permissions:
  contents: read

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm ci
      - name: Run eslint
        run: |
          npm run lint
